apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-emptydir
  name: k8s-emptydir
spec:
  selector:
    matchLabels:
      app: k8s-emptydir
  template:
    metadata:
      labels:
        app: k8s-emptydir
    spec:
      containers:
        - image: consumer:latest
          imagePullPolicy: IfNotPresent
          name: consumer
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          volumeMounts:
            - mountPath: /static
              name: exchange
        - image: producer:latest
          imagePullPolicy: IfNotPresent
          name: producer
          volumeMounts:
            - mountPath: /static
              name: exchange
      volumes:
        - name: exchange
          emptyDir: {}
